apps:
  - name: 'movie-server'
    script: ./server/bin/www
    instances: max
    exec_mode: cluster
    max_memory_restart: 500M
    autorestart: true
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
